#!/bin/bash

#PBS -q studenti
#PBS -l nodes=8:ppn=8
#PBS -l mem=2GB
#PBS -N matmatdist
#PBS -o matmatdist_output.txt
#PBS -e matmatdist_output.err

cd $PBS_O_WORKDIR

MPI_DIR=/usr/lib64/openmpi/1.4-gcc/bin

sort -u $PBS_NODEFILE > machinefile
NCPU=`wc -l < machinefile`

echo "Il job è in esecuzione sugli $NCPU nodi:"
cat machinefile

make CC="$MPI_DIR/mpicc" -j

echo "-------------------------------------"
$MPI_DIR/mpiexec -np 4 -machinefile machinefile $PBS_O_WORKDIR/main.exe